# Generated by Django 5.2.1 on 2025-06-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_listing_ref_id_contact_user_ref_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing_ref_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_ref_id',
        ),
    ]
